=== ErTreK8/1-Month-of-learning-JavaScript-2024-/UF2/EJ3 cosa rara/ex4.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="biblioteca">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="llibre" type="llibres"/>
        </xs:sequence>
    </xs:complexType>  
</xs:element>
<xs:complexType name="llibres">
    <xs:sequence>
        <xs:element name="titol" type="xs:string"/>
        <xs:element name="publicacio" type="xs:string"/>
        <xs:element name="autor" type="autores"/>
        <xs:element name="premis" type="premios"/>
        <xs:element name="argument" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="autores">
    <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="cognom" type="xs:string" maxOccurs="2"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="premios">
    <xs:sequence>
        <xs:element name="premi" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
</xs:schema>

=== ErTreK8/1-Month-of-learning-JavaScript-2024-/UF2/EJ3 cosa rara/ex4.xml
<?xml version="1.0"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ex4.xsd">
    <llibre>           
        <titol>Patatim</titol>
        <publicacio>14 de maig de 2008</publicacio>
        <autor>
            <nom>Federicu</nom>  
            <cognom>Pi</cognom>
            <cognom>Torrat</cognom>
        </autor>
        <premis>
            <premi>Premi Planeta 2008</premi>
            <premi>Premi Social 2009</premi>
        </premis>
        <argument>
            La hist√≤ria va de patatim, patatam, patatum... 
        </argument>
    </llibre>
</biblioteca>
